### ISSUE TITLE
What the TF-IDF retriever data output mean

### ISSUE THREAD

**Issue by ajesujoba** [AkariAsai/learning_to_retrieve_reasoning_paths#19]
Thanks for the good work. Just to be sure I understand the paper and implementation correctly,
1. does the graph retriever model extract paragraphs from another source except from the output data from the TF-IDF retrieval output during training and inference?
2. Going by the TF-IDF output format

```
{
"question": 'Were Scott Derrickson and Ed Wood of the same nationality?'.
"q_id": "5ab3b0bf5542992ade7c6e39",
"context":
    {"Scott Derrickson_0": "Scott Derrickson (born July 16, 1966) is an American director,....",
      "Ed Wood'_0": "...", ....},
'all_linked_para_title_dic':
    {"Scott Derrickson_0": ['Los Angeles_0', 'California_0', 'Horror film_0', ...]},
'all_linked_paras_dic':
    {"Los Angeles_0": "Los Angeles, officially the City of Los Angeles and often known by its initials L.A., is ...", ...},
'short_gold':[],
'redundant_gold': [],
'all_redundant_gold': []
}

```
Am I correct to say that
` C_1 = context `
` C_2 = any of the **all_linked_para_title_dic** `  as extracted by the graph based retriever?

Am I also correct to say that the data format would work only for questions that need to be answered in at-most 2-hops?

Sorry if my questions are too basic

**Comment by AkariAsai** [comment]
Hi, thanks for asking great questions! Please see the answers below, and feel free to post followup questions if you have any. 

> does the graph retriever model extract paragraphs from another source except for the output data from the TF-IDF retrieval output during training and inference?

As mentioned in our paper, we also include Wikipedia articles selected by TagMe only for NQ. We do not try this for HotpotQA or SQuAD Open during the inference process. 

> C_2 = any of the **all_linked_para_title_dic**

C_2 can be the paragraph that are linked from the title selected from the previous step, so `Titles in C_2 = all_linked_para_title_dic[title_selected_from_previous_time_step]`. We also include the top 2 and 3 paragraphs from the previous time step. This is because sometimes the paragraphs related to the question are not connected by entities from the first paragraph. For example in HotpotQA, a question may ask "which person is older, person X and person Y?", and the paragraphs on person X and person Y are not necessarily be connected with each other via hyper links.

**Comment by ajesujoba** [comment]
Oh! Thanks @AkariAsai . Now I understand better. 

The following questions are not follow up questions to the earlier question, 
1. On this GitHub page, it is written that `We are planning to release our codes to augment training data with negative examples and distant examples to guide future research in open-domain QA fields. Please stay tuned!`, are you releasing the codes anytime soon?

2. Is it possible to train a model basically for distractor setting using the codes here? I have got questions and some corresponding paragraphs that should answer the questions (with no entity linking), can your model work in this case?

**Comment by AkariAsai** [comment]
Hi so sorry for my late response! 

> We are planning to release our codes to augment training data with negative examples and distant examples to guide future research in open-domain QA fields. Please stay tuned!

I could share the script we use for data creation, although it's not well documented or cleaned up. Due to the current ongoing projects, I'm not sure if I could take enough time to clean those scripts up to release... 

> Is it possible to train a model basically for distractor setting using the codes here? I have got questions and some corresponding paragraphs that should answer the questions (with no entity linking), can your model work in this case?

I think you can train the model on distractor settings, but if your questions do not require multi-hop reasoning across entities, simple BERT-based paragraph ranking models (e.g., [Nogueira and Cho 2020](https://arxiv.org/pdf/1901.04085.pdf)) might be sufficient.
