### ISSUE TITLE
Preprocessing of HotpotQA

### ISSUE THREAD

**Issue by talkhaldi** [AkariAsai/learning_to_retrieve_reasoning_paths#3]
Hi,

Thank you for your work and sharing your code!

I have some questions about the file you provide: "HotpotQA reader train data". Can you please point/share the preprocessing code that gives "answer starts", because the original hotpotqa training data doesn't have this. Also, in that file, are all yes/no regarded as "is_impossible=True"?

**Comment by AkariAsai** [comment]
> Can you please point/share the preprocessing code that gives "answer starts", because the original hotpotqa training data doesn't have this. 

We simply mark the first span in the gold paragraphs matching the original answer as the answer starts. We are preparing to release the codes we use to create the train data for reader & graph retriever as well.

The _first only_  solution might be suboptimal as the spans matching the original answer may appear multiple times in the gold paragraphs, and the first span might not entail the question. 
We could incorporate some approaches (e.g., [MML](https://www.aclweb.org/anthology/P18-1078/) or [Hard EM](https://www.aclweb.org/anthology/D19-1284/)) to handle multiple answer spans when only answer strings are given, but we leave that part as other two datasets (SQuAD and Natural Questions) provide span-level annotations. 
We also observe that in HotpotQA, the first spans in the paragraph matching the original answer string generally entails questions, maybe due to the dataset bias as discussed in [Hard EM paper](https://www.aclweb.org/anthology/D19-1284/). 

>  Also, in that file, are all yes/no regarded as "is_impossible=True"

Yes; the `is_impossible` means _we cannot find the answer span in the original paragraphs_ and thus we set `is_impossible` to `True` for yes/no questions. 

Please let me know if you have further questions!

**Comment by talkhaldi** [comment]
Thanks a lot for your clarification! 

I'm looking forward to seeing your preprocessing code. In the meanwhile, I'm using this: 
[https://github.com/shmsw25/DecompRC/blob/master/DecompRC/prepro_util.py#L68](code)

Do you have any statistic/number on how often the first matching answer entails the question?

Also a note related to preprocessing, I found some (94) empty paragraphs from the fullwiki data. I also found some questions in the training data with supporting facts pointing to non existent sentence. (Example: qid: "5a7b23ca554299042af8f703" sf: ['Minoru Suzuki', 2] -- Paragraph has only 2 sentences (0,1)!)

**Comment by AkariAsai** [comment]
> Do you have any statistics/numbers on how often the first matching answer entails the question?

I don't have exact statistics right now, but when I analyzed 100 examples randomly sampled from HotpotQA dev set, I don't see many questions where the spans selected by _first only_ heuristics can be spurious. 

> Also a note related to preprocessing, I found some (94) empty paragraphs from the fullwiki data. I also found some questions in the training data with supporting facts pointing to non existent sentence. (Example: qid: "5a7b23ca554299042af8f703" sf: ['Minoru Suzuki', 2] -- Paragraph has only 2 sentences (0,1)!)

Thank you for reporting the bug! We'll fix it soon.
